### ISSUE TITLE
Contributors License Agreement (CLA)

### ISSUE THREAD

**Issue by evenh** [PayEx/PayEx.Development.Guidelines#2]
For legal purposes - do we need contributors to sign a CLA for contributions? If so, [CLA assistant](https://cla-assistant.io/) seems like a viable option.

**Comment by asbjornu** [comment]
@evenh Great idea! But I think the assertions in the "Patent License" section are more hostile than necessary and incompatible with the proposed [MIT License](https://opensource.org/licenses/MIT):

> **Patent License.** You hereby grant, and agree to grant, to PayEx a non-exclusive, perpetual, irrevocable, worldwide, fully-paid, royalty-free, transferable patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer your Contributions, where such license applies only to those patent claims licensable by you that are necessarily infringed by your Contributions alone or by combination of your Contributions with the Project to which such Contributions were submitted, with the right to sublicense the foregoing rights through multiple tiers of sublicensees.

I think contributions should fall under a [CC BY-SA](http://creativecommons.org/licenses/by-sa/4.0/) or [MIT](https://opensource.org/licenses/MIT) license, so the contributors are free to use the contributed code as they wish. Ideas on how we can accomplish that? We can of course just remove the section, but some kind of assertions regarding patents and copyright is probably wise.

**Comment by evenh** [comment]
I agree that the wording sound pretty hostile, but unfortunately I don't speak legalese. I think we should consider clarify this internally so that the legal aspects are covered -- hopefully we'll find a way to license the contributions under a liberal license as well :-).

**Comment by asbjornu** [comment]
I've sent off an e-mail to legal to see if they can help us out. Meanwhile I've [forked the CLA](https://gist.github.com/asbjornu/f0d2a66c22a58da55b61), so please have a whack at it if you figure out some brilliant wording we can put into it. :)

**Comment by evenh** [comment]
Any news from the legal department?

**Comment by asbjornu** [comment]
@evenh: No news, no. 😕

**Comment by asbjornu** [comment]
@evenh: We have news! I just had a great talk with legal and they told me they saw no problem with the agreement in terms of what the contributor keeps the rights to. The agreement only ensures that PayEx can do whatever we want with the contributed code.

**Comment by asbjornu** [comment]
I have now updated [the gist](https://gist.github.com/asbjornu/f0d2a66c22a58da55b61) with the proposed introduction. I think it needs a bit of revision, but it's a start:
> Contrary to “Closed Source” software or proprietary software – where a creator maintains exclusive control over his or hers source code – “Open Software” is software with source code that anyone can inspect, modify, share, learn from and enhance. Outlined below you will find PayEx Individual Contributor License Agreement under which you as a contributor retain all of your right, title and interest in and to your contributions with the exception of mainly two licenses, a non-exclusive Copyright License as well as a non-exclusive Patent License, whereby you as a contributor offer PayEx certain rights e.g. of usage alteration and sharing, in relation to your contributions.
>
>A very sincere thank you for your valuable contributions!

**Comment by asbjornu** [comment]
@evenh: The CLA has been linked. Want to test it out either in this repo or in [design.payex.com](https://github.com/PayEx/design.payex.com)?

**Comment by evenh** [comment]
Seems to work: https://github.com/PayEx/design.payex.com/pull/35 :-)

**Comment by asbjornu** [comment]
Perfect!
